# crie um pipeline do GitHub Actions para build de uma aplicação .net 6

name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release --no-build --no-restore --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./publish

# inclua um upload artifact para a pasta ./bicep

      - name: Upload Bicep
        uses: actions/upload-artifact@v2
        with:
          name: bicep
          path: ./bicep



  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: publish
          path: ./publish

      - uses:  actions/download-artifact@v2
        with:
          name: bicep
          path: ./bicep
      
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy
        run: |
          az deployment group create --resource-group ${{ secrets.RESOURCE_GROUP }} --template-file ./bicep/sample.bicep 

      - uses: azure/webapps-deploy@v2
        with:
          app-name: demo-app-service-bicep-arruda
          package: ./publish


